### ISSUE TITLE
Prevent temporary connection problems from kicking a player out

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_shiny_web_app#21]
When server-side Shiny cannot communicate with the client, even if it's for a moment, the window grays out and the session is lost. 

Upon refresh, a new session is initiated and the player will not be able to rejoin the same game, as the player UUID was stored in the session.

With Shiny Server (incl. the open-source version), this can be somewhat alleviated - interruptions lasting 15 seconds at maximum will not kill the session. However, longer interruptions and accidental manually triggered refreshes on phones will still do it.

I can see the following options: 

- we are fine with the imperfect solution implemented in Shiny Server and run the app using Shiny Server;
- we store user data on the server outside of a session. This would mean associating variables with e.g. user IPs and, upon a user starting a fresh session, letting them retrieve the last state of the server-side reactive variables in a session initiated from their IP. There are potential privacy / legal concerns here;
- we store user data in cookies, but we may again run into privacy / legal issues here; or
- we allow the user (and strongly recommend them) to save the `game_uuid`, `player_uuid` and `nickname` in a `csv` file on their device using a button in the game scene - and then let them read that file in using a different button in the lobby scene.

I'm leaning towards the first + last solution.

**Comment by adrian-golian** [comment]
We can just say “Copy and *keep* this ID if you want to rejoin the game later!”

**Comment by adrian-golian** [comment]
Otherwise, I’d lean towards the standard approach to sessions - cookies.

**Comment by maciej-pomykala** [comment]
I guess asking people to keep their player UUID is not a bad option. All it takes is them copying their UUID into their clipboards and storing it somewhere or not deleting it until the game ends.

Otherwise, we might display their player UUID in a field in the table. When the app grays out, I believe they can still see and copy the last things they saw before the termination.

**Comment by adrian-golian** [comment]
The other use case is if someone closes the tab accidentally - in which case you either need to have copied/saved the IDs (game and player), or have a cookie.

**Comment by maciej-pomykala** [comment]
[This](https://shiny.rstudio.com/reference/shiny/1.4.0/updateQueryString.html) and [this](https://stackoverflow.com/questions/25112132/how-to-generate-a-url-to-restore-the-user-input-values-in-shiny) are interesting resources on another solution - storing `game_uuid`, `player_uuid` and `nickname` in the URL and loading them in if the user refreshes the page.

**Comment by maciej-pomykala** [comment]
Right - using URLs, it took me minutes to solve the problem. If you agree with the principle, I'll carefully check and polish my solution and commit it onto the appropriate issue branch.

**Comment by adrian-golian** [comment]
Sounds good!
