### ISSUE TITLE
Improve game scene style

### ISSUE THREAD

**Issue by maciej-pomykala** [Blef-team/blef_shiny_web_app#46]
There are various styling improvements that could be applied to the game scene.

These can be:

- reduce top and left margins (helpful for phones until we deploy apps for all phone operating systems);
- increase the card image size slightly (from 40 to, say, 45 or 50) - especially helpful for distinguishing spades and clubs;
- rename 'History' to 'Actions so far';
- convert 'Game public' and 'Maximum allowed cards' information to images. The former would become a simple globe icon with a tick mark or a cross mark (and text on hover). The latter would become an icon presenting two cards, one slightly tilted, the word 'max' below them and a nicely styled number to the right - all of it in an icon with many versions depending on the number (also with a text on hover); and
- when presenting round results, do not display cards to the right of nickname, but rather below it, as currently larger hands need 2-3 rows to be displayed while long nicknames occupy very big cells in the table.

**Comment by adrian-golian** [comment]
Sounds good. How about also replacing the player nickname with “you”?

**Comment by maciej-pomykala** [comment]
That's a good suggestion for #32, which deals with this

**Comment by maciej-pomykala** [comment]
Resolved via various PRs
